syntax on
filetype plugin indent on
packloadall

let $RTP=split(&runtimepath, ',')[0]
let $RC="~/.vim/vimrc"
let mapleader = " "

set shiftwidth=4 
set tabstop=4
set softtabstop=4 
set expandtab 
set autoindent 
set smartindent
set exrc
set nocompatible
set backspace=indent,eol,start
set nowrap
set path=.,**
set nu
set relativenumber
set completeopt=menuone,noinsert,noselect
set spell
set nohlsearch
set colorcolumn=80
set signcolumn=yes
set cmdheight=2
set updatetime=50
set guicursor=
set shortmess+=c
set encoding=UTF-8
set mouse=a
set background=dark
set completeopt=longest,menuone
set nospell
set omnifunc=syntaxcomplete#Complete
set scrolloff=8
set laststatus=2
set hidden
set termguicolors

colorscheme gruvbox
hi Normal guibg=NONE ctermbg=NONE
function! GitBranch()
  return system("git rev-parse --abbrev-ref HEAD 2>/dev/null | tr -d '\n'")
endfunction

function! StatuslineGit()
  let l:branchname = GitBranch()
  return strlen(l:branchname) > 0?'  '.l:branchname.' ':''
endfunction

set statusline=
set statusline+=%#PmenuSel#
set statusline+=%{StatuslineGit()}
set statusline+=%#LineNr#
set statusline+=\ %f
set statusline+=%m
set statusline+=%=
set statusline+=%#CursorColumn#
set statusline+=\ %y
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
set statusline+=\[%{&fileformat}\]
set statusline+=\ %p%%
set statusline+=\ %l:%c
